export type Country = {
  value: string;
  flag: string;
  name: string;
};

export const COUNTRIES: Country[] = [
  // ── Europe francophone ──────────────────────────────
  { value: 'france',          flag: '🇫🇷', name: 'France' },
  { value: 'belgique',        flag: '🇧🇪', name: 'Belgique' },
  { value: 'suisse',          flag: '🇨🇭', name: 'Suisse' },
  { value: 'luxembourg',      flag: '🇱🇺', name: 'Luxembourg' },
  { value: 'monaco',          flag: '🇲🇨', name: 'Monaco' },
  // ── Europe ─────────────────────────────────────────
  { value: 'espagne',         flag: '🇪🇸', name: 'Espagne' },
  { value: 'italie',          flag: '🇮🇹', name: 'Italie' },
  { value: 'allemagne',       flag: '🇩🇪', name: 'Allemagne' },
  { value: 'portugal',        flag: '🇵🇹', name: 'Portugal' },
  { value: 'royaumeuni',      flag: '🇬🇧', name: 'Royaume-Uni' },
  { value: 'paysbas',         flag: '🇳🇱', name: 'Pays-Bas' },
  { value: 'autriche',        flag: '🇦🇹', name: 'Autriche' },
  { value: 'suede',           flag: '🇸🇪', name: 'Suède' },
  { value: 'norvege',         flag: '🇳🇴', name: 'Norvège' },
  { value: 'danemark',        flag: '🇩🇰', name: 'Danemark' },
  { value: 'finlande',        flag: '🇫🇮', name: 'Finlande' },
  { value: 'pologne',         flag: '🇵🇱', name: 'Pologne' },
  { value: 'roumanie',        flag: '🇷🇴', name: 'Roumanie' },
  { value: 'grece',           flag: '🇬🇷', name: 'Grèce' },
  { value: 'hongrie',         flag: '🇭🇺', name: 'Hongrie' },
  { value: 'tcheque',         flag: '🇨🇿', name: 'Rép. Tchèque' },
  { value: 'croatie',         flag: '🇭🇷', name: 'Croatie' },
  { value: 'serbie',          flag: '🇷🇸', name: 'Serbie' },
  { value: 'ukraine',         flag: '🇺🇦', name: 'Ukraine' },
  { value: 'russie',          flag: '🇷🇺', name: 'Russie' },
  { value: 'turquie',         flag: '🇹🇷', name: 'Turquie' },
  // ── Afrique du Nord & Moyen-Orient ────────────────
  { value: 'maroc',           flag: '🇲🇦', name: 'Maroc' },
  { value: 'algerie',         flag: '🇩🇿', name: 'Algérie' },
  { value: 'tunisie',         flag: '🇹🇳', name: 'Tunisie' },
  { value: 'libye',           flag: '🇱🇾', name: 'Libye' },
  { value: 'egypte',          flag: '🇪🇬', name: 'Égypte' },
  { value: 'mauritanie',      flag: '🇲🇷', name: 'Mauritanie' },
  { value: 'liban',           flag: '🇱🇧', name: 'Liban' },
  { value: 'jordanie',        flag: '🇯🇴', name: 'Jordanie' },
  { value: 'arabie-saoudite', flag: '🇸🇦', name: 'Arabie Saoudite' },
  { value: 'emirats',         flag: '🇦🇪', name: 'Émirats Arabes' },
  { value: 'qatar',           flag: '🇶🇦', name: 'Qatar' },
  { value: 'koweit',          flag: '🇰🇼', name: 'Koweït' },
  { value: 'israel',          flag: '🇮🇱', name: 'Israël' },
  // ── Afrique subsaharienne ──────────────────────────
  { value: 'senegal',             flag: '🇸🇳', name: 'Sénégal' },
  { value: 'cote-divoire',        flag: '🇨🇮', name: "Côte d'Ivoire" },
  { value: 'cameroun',            flag: '🇨🇲', name: 'Cameroun' },
  { value: 'mali',                flag: '🇲🇱', name: 'Mali' },
  { value: 'burkina-faso',        flag: '🇧🇫', name: 'Burkina Faso' },
  { value: 'niger',               flag: '🇳🇪', name: 'Niger' },
  { value: 'togo',                flag: '🇹🇬', name: 'Togo' },
  { value: 'benin',               flag: '🇧🇯', name: 'Bénin' },
  { value: 'guinee',              flag: '🇬🇳', name: 'Guinée' },
  { value: 'gabon',               flag: '🇬🇦', name: 'Gabon' },
  { value: 'congo-brazzaville',   flag: '🇨🇬', name: 'Congo-Brazzaville' },
  { value: 'rdc',                 flag: '🇨🇩', name: 'RD Congo (Kinshasa)' },
  { value: 'madagascar',          flag: '🇲🇬', name: 'Madagascar' },
  { value: 'ile-maurice',         flag: '🇲🇺', name: 'Île Maurice' },
  { value: 'rwanda',              flag: '🇷🇼', name: 'Rwanda' },
  { value: 'nigeria',             flag: '🇳🇬', name: 'Nigeria' },
  { value: 'ghana',               flag: '🇬🇭', name: 'Ghana' },
  { value: 'kenya',               flag: '🇰🇪', name: 'Kenya' },
  { value: 'tanzanie',            flag: '🇹🇿', name: 'Tanzanie' },
  { value: 'ethiopie',            flag: '🇪🇹', name: 'Éthiopie' },
  { value: 'afrique-du-sud',      flag: '🇿🇦', name: 'Afrique du Sud' },
  { value: 'angola',              flag: '🇦🇴', name: 'Angola' },
  { value: 'mozambique',          flag: '🇲🇿', name: 'Mozambique' },
  // ── Amérique ──────────────────────────────────────
  { value: 'usa',         flag: '🇺🇸', name: 'États-Unis' },
  { value: 'canada',      flag: '🇨🇦', name: 'Canada' },
  { value: 'mexique',     flag: '🇲🇽', name: 'Mexique' },
  { value: 'bresil',      flag: '🇧🇷', name: 'Brésil' },
  { value: 'argentine',   flag: '🇦🇷', name: 'Argentine' },
  { value: 'colombie',    flag: '🇨🇴', name: 'Colombie' },
  { value: 'chili',       flag: '🇨🇱', name: 'Chili' },
  { value: 'perou',       flag: '🇵🇪', name: 'Pérou' },
  { value: 'venezuela',   flag: '🇻🇪', name: 'Venezuela' },
  // ── Asie & Océanie ────────────────────────────────
  { value: 'inde',          flag: '🇮🇳', name: 'Inde' },
  { value: 'pakistan',      flag: '🇵🇰', name: 'Pakistan' },
  { value: 'chine',         flag: '🇨🇳', name: 'Chine' },
  { value: 'japon',         flag: '🇯🇵', name: 'Japon' },
  { value: 'coree-du-sud',  flag: '🇰🇷', name: 'Corée du Sud' },
  { value: 'indonesie',     flag: '🇮🇩', name: 'Indonésie' },
  { value: 'philippines',   flag: '🇵🇭', name: 'Philippines' },
  { value: 'thailand',      flag: '🇹🇭', name: 'Thaïlande' },
  { value: 'vietnam',       flag: '🇻🇳', name: 'Vietnam' },
  { value: 'australie',     flag: '🇦🇺', name: 'Australie' },
];

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.value, c]));
export const COUNTRY_FLAGS: Record<string, string> = Object.fromEntries(COUNTRIES.map(c => [c.value, c.flag]));
export const COUNTRY_NAMES: Record<string, string> = Object.fromEntries(COUNTRIES.map(c => [c.value, c.name]));
