import { db, categoriesTable, productsTable, usersTable } from "@workspace/db";
import { eq, sql } from "drizzle-orm";

async function seed() {
  console.log("🌱 Seeding database...");

  // Categories
  const existingCategories = await db.select().from(categoriesTable);
  if (existingCategories.length === 0) {
    await db.insert(categoriesTable).values([
      { name: "NUMLIST", slug: "numlist", description: "Listes de numéros de téléphone vérifiés" },
      { name: "MAILLIST", slug: "maillist", description: "Bases d'emails opt-in vérifiés" },
      { name: "FICHE CLIENT", slug: "fiche-client", description: "Fiches clients complètes" },
    ]);
    console.log("✅ Categories created");
  }

  const existingProducts = await db.select().from(productsTable);
  if (existingProducts.length === 0) {
    const categories = await db.select().from(categoriesTable);
    const numlistCat = categories.find(c => c.slug === "numlist");
    const maillistCat = categories.find(c => c.slug === "maillist");
    const ficheCat = categories.find(c => c.slug === "fiche-client");

    await db.insert(productsTable).values([
      // ── NUMLIST ──
      {
        name: "NUMLIST 🇫🇷 France — 500K numéros",
        description: "Base de 500 000 numéros de téléphone français vérifiés et actifs. Format CSV, triés par région, opt-in confirmé.",
        price: "49.99",
        fileUrl: null,
        fileName: "numlist_france_500k.csv",
        fileType: "CSV",
        fileSize: 18000000,
        categoryId: numlistCat?.id,
        tags: ["numlist", "france", "téléphone"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: true,
        isNew: false,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "NUMLIST 🇧🇪 Belgique — 200K numéros",
        description: "200 000 numéros mobiles belges actifs. Segmentés par province (Bruxelles, Liège, Anvers...). Format CSV.",
        price: "34.99",
        fileUrl: null,
        fileName: "numlist_belgique_200k.csv",
        fileType: "CSV",
        fileSize: 7200000,
        categoryId: numlistCat?.id,
        tags: ["numlist", "belgique", "téléphone"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "NUMLIST 🇲🇦 Maroc — 300K numéros",
        description: "300 000 numéros marocains actifs. Opérateurs : Maroc Telecom, Orange, Inwi. Format CSV.",
        price: "29.99",
        fileUrl: null,
        fileName: "numlist_maroc_300k.csv",
        fileType: "CSV",
        fileSize: 10800000,
        categoryId: numlistCat?.id,
        tags: ["numlist", "maroc", "téléphone"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: true,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "NUMLIST 🇨🇭 Suisse — 100K numéros",
        description: "100 000 numéros suisses premium. Cantons francophones et germanophones. Format CSV.",
        price: "59.99",
        fileUrl: null,
        fileName: "numlist_suisse_100k.csv",
        fileType: "CSV",
        fileSize: 3600000,
        categoryId: numlistCat?.id,
        tags: ["numlist", "suisse", "téléphone"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "NUMLIST 🇩🇿 Algérie — 400K numéros",
        description: "400 000 numéros algériens vérifiés. Opérateurs : Djezzy, Mobilis, Ooredoo. Format CSV.",
        price: "24.99",
        fileUrl: null,
        fileName: "numlist_algerie_400k.csv",
        fileType: "CSV",
        fileSize: 14400000,
        categoryId: numlistCat?.id,
        tags: ["numlist", "algerie", "téléphone"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },

      // ── MAILLIST ──
      {
        name: "MAILLIST 🇫🇷 France — 1M emails",
        description: "1 000 000 adresses email françaises opt-in. Taux de délivrabilité > 95%. Segmentées par secteur (e-commerce, santé, finance). Format CSV.",
        price: "79.99",
        fileUrl: null,
        fileName: "maillist_france_1m.csv",
        fileType: "CSV",
        fileSize: 35000000,
        categoryId: maillistCat?.id,
        tags: ["maillist", "france", "email"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: true,
        isNew: false,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "MAILLIST 🇧🇪 Belgique — 300K emails",
        description: "300 000 emails belges vérifiés opt-in. Séparés par langue (FR/NL). Format CSV.",
        price: "39.99",
        fileUrl: null,
        fileName: "maillist_belgique_300k.csv",
        fileType: "CSV",
        fileSize: 10500000,
        categoryId: maillistCat?.id,
        tags: ["maillist", "belgique", "email"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "MAILLIST 🇨🇦 Canada — 500K emails",
        description: "500 000 emails canadiens opt-in, conformes CASL. Provinces : QC, ON, BC. Format CSV.",
        price: "49.99",
        fileUrl: null,
        fileName: "maillist_canada_500k.csv",
        fileType: "CSV",
        fileSize: 17500000,
        categoryId: maillistCat?.id,
        tags: ["maillist", "canada", "email"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "MAILLIST 🇲🇦 Maroc — 400K emails",
        description: "400 000 emails marocains actifs. Professionnels et particuliers. Format CSV.",
        price: "29.99",
        fileUrl: null,
        fileName: "maillist_maroc_400k.csv",
        fileType: "CSV",
        fileSize: 14000000,
        categoryId: maillistCat?.id,
        tags: ["maillist", "maroc", "email"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: true,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "MAILLIST 🇹🇳 Tunisie — 200K emails",
        description: "200 000 emails tunisiens opt-in. Secteurs : commerce, tourisme, services. Format CSV.",
        price: "19.99",
        fileUrl: null,
        fileName: "maillist_tunisie_200k.csv",
        fileType: "CSV",
        fileSize: 7000000,
        categoryId: maillistCat?.id,
        tags: ["maillist", "tunisie", "email"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },

      // ── FICHE CLIENT ──
      {
        name: "FICHE CLIENT 🇫🇷 France — 50K entreprises",
        description: "50 000 fiches entreprises françaises : nom, SIRET, email, téléphone, adresse, secteur, chiffre d'affaires. Format CSV.",
        price: "89.99",
        fileUrl: null,
        fileName: "ficheclient_france_50k.csv",
        fileType: "CSV",
        fileSize: 25000000,
        categoryId: ficheCat?.id,
        tags: ["fiche-client", "france", "entreprise"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: true,
        isNew: false,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "FICHE CLIENT 🇫🇷 France — Particuliers 100K",
        description: "100 000 fiches particuliers France : prénom, nom, email, téléphone, ville, code postal. Format CSV.",
        price: "69.99",
        fileUrl: null,
        fileName: "ficheclient_france_particuliers_100k.csv",
        fileType: "CSV",
        fileSize: 20000000,
        categoryId: ficheCat?.id,
        tags: ["fiche-client", "france", "particulier"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "FICHE CLIENT 🇲🇦 Maroc — 20K entreprises",
        description: "20 000 fiches entreprises marocaines : nom, ICE, email, téléphone, ville, secteur. Format CSV.",
        price: "44.99",
        fileUrl: null,
        fileName: "ficheclient_maroc_20k.csv",
        fileType: "CSV",
        fileSize: 8000000,
        categoryId: ficheCat?.id,
        tags: ["fiche-client", "maroc", "entreprise"],
        imageUrl: null,
        isActive: true,
        isFeatured: true,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "FICHE CLIENT 🇧🇪 Belgique — 15K entreprises",
        description: "15 000 fiches PME belges : nom, TVA, email, téléphone, adresse. Format CSV.",
        price: "54.99",
        fileUrl: null,
        fileName: "ficheclient_belgique_15k.csv",
        fileType: "CSV",
        fileSize: 5400000,
        categoryId: ficheCat?.id,
        tags: ["fiche-client", "belgique", "entreprise"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
      {
        name: "FICHE CLIENT 🇩🇿 Algérie — 10K entreprises",
        description: "10 000 fiches entreprises algériennes : raison sociale, NIF, email, téléphone, wilaya. Format CSV.",
        price: "34.99",
        fileUrl: null,
        fileName: "ficheclient_algerie_10k.csv",
        fileType: "CSV",
        fileSize: 3600000,
        categoryId: ficheCat?.id,
        tags: ["fiche-client", "algerie", "entreprise"],
        imageUrl: null,
        isActive: true,
        isFeatured: false,
        isBestSeller: false,
        isNew: true,
        downloadLimit: 3,
        downloadExpiry: 7,
      },
    ]);
    console.log("✅ Products created (", 15, "products)");
  } else {
    console.log("ℹ️  Products already exist, skipping.");
  }

  console.log("🎉 Seeding complete!");
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
